-- phpMyAdmin SQL Dump
-- version 5.0.4
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Waktu pembuatan: 17 Jan 2021 pada 07.53
-- Versi server: 10.4.17-MariaDB
-- Versi PHP: 8.0.0

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `db_stylon.com`
--

-- --------------------------------------------------------

--
-- Struktur dari tabel `db_admin`
--

CREATE TABLE `db_admin` (
  `admin_id` int(11) NOT NULL,
  `admin_name` varchar(50) NOT NULL,
  `username` varchar(50) NOT NULL,
  `password` varchar(100) NOT NULL,
  `admin_telp` varchar(20) NOT NULL,
  `admin_email` varchar(50) NOT NULL,
  `admin_addres` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data untuk tabel `db_admin`
--

INSERT INTO `db_admin` (`admin_id`, `admin_name`, `username`, `password`, `admin_telp`, `admin_email`, `admin_addres`) VALUES
(1, 'Nur Anisah', 'admin', '81dc9bdb52d04dc20036dbd8313ed055', '+6282272538581', 'nur.200170015@mhs.unimal.ac.id', 'Desa Paya Tukai, Kecamatan Langkahan, Kabupaten Aceh Utara');

-- --------------------------------------------------------

--
-- Struktur dari tabel `db_category`
--

CREATE TABLE `db_category` (
  `category_id` int(11) NOT NULL,
  `category_name` varchar(25) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data untuk tabel `db_category`
--

INSERT INTO `db_category` (`category_id`, `category_name`) VALUES
(7, 'Hijab'),
(11, 'Busana'),
(12, 'Aksesoris');

-- --------------------------------------------------------

--
-- Struktur dari tabel `dp_product`
--

CREATE TABLE `dp_product` (
  `product_id` int(11) NOT NULL,
  `category_id` int(11) NOT NULL,
  `product_name` varchar(100) NOT NULL,
  `product_price` int(11) NOT NULL,
  `product_description` text NOT NULL,
  `product_images` varchar(100) NOT NULL,
  `product_status` tinyint(1) NOT NULL,
  `date_created` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data untuk tabel `dp_product`
--

INSERT INTO `dp_product` (`product_id`, `category_id`, `product_name`, `product_price`, `product_description`, `product_images`, `product_status`, `date_created`) VALUES
(6, 7, 'Monochrome Scarlet Black', 200000, '\r\n<p>INFORMASI PRODUK<br />\r\n<br />\r\nMonochrome Series<br />\r\n<br />\r\n- Ukuran: 115 x 115 cm<br />\r\n- Bahan: Voal Premium<br />\r\n- Finishing: Laser Cut<br />\r\n<br />\r\nKesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)&nbsp;</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\n<br />\r\nMonochrome Series</p>\r\n\r\n<p>- Size : 115 x 115 cm<br />\r\n- Material : Voal Premium<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone)</p>\r\n', 'produk1610768789.jpg', 1, '2021-01-16 03:46:29'),
(7, 7, 'Banara Yellow', 250000, '<p>INFORMASI PRODUK<br />\r\n<br />\r\nBanara Series<br />\r\n<br />\r\n- Ukuran: 115 x 115 cm<br />\r\n- Bahan: Voal Premium<br />\r\n- Finishing: Laser Cut<br />\r\n<br />\r\nKesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)&nbsp;</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\n<br />\r\nBanara Series</p>\r\n\r\n<p>- Size : 115 x 115 cm<br />\r\n- Material : Voal Premium<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone)</p>\r\n', 'produk1610769002.jpg', 1, '2021-01-16 03:50:02'),
(8, 7, 'Flower Maroon', 225000, '<p>INFORMASI PRODUK<br />\r\n<br />\r\nFlower Series<br />\r\n<br />\r\n- Ukuran: 115 x 115 cm<br />\r\n- Bahan: Voal Premium<br />\r\n- Finishing: Laser Cut<br />\r\n<br />\r\nKesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)&nbsp;</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\n<br />\r\nFlower Series</p>\r\n\r\n<p>- Size : 115 x 115 cm<br />\r\n- Material : Voal Premium<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone)</p>\r\n\r\n<p>Material : Premium Voal (lembut, adem, mudah dibentuk, tegak sempurna di dahi). &nbsp;Finishing Laser cut.&nbsp;Laser cut berbentuk awan yang unik. Size : 115cm X 115cm With Packaging Box Spot UV</p>\r\n', 'produk1610769177.jpg', 1, '2021-01-16 03:52:57'),
(9, 7, 'Polka Yellow', 225000, '<p>INFORMASI PRODUK<br />\r\n<br />\r\nPolka<br />\r\n<br />\r\n- Ukuran: 115 x 115 cm<br />\r\n- Bahan: Voal Premium<br />\r\n- Finishing: Laser Cut<br />\r\n<br />\r\nKesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)&nbsp;</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\n<br />\r\nPolka</p>\r\n\r\n<p>- Size : 115 x 115 cm<br />\r\n- Material : Voal Premium<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone)</p>\r\n\r\n<p>Material : Premium Voal (lembut, adem, mudah dibentuk, tegak sempurna di dahi). &nbsp;Finishing Laser cut.&nbsp;Laser cut berbentuk awan yang unik. Size : 115cm X 115cm With Packaging Box Spot UV</p>\r\n', 'produk1610769280.jpg', 1, '2021-01-16 03:54:40'),
(10, 7, 'Ayana Grey', 225000, '<p>NFORMASI PRODUK<br />\r\n<br />\r\nAyana<br />\r\n<br />\r\n- Ukuran: 115 x 115 cm<br />\r\n- Bahan: Voal Premium<br />\r\n- Finishing: Laser Cut<br />\r\n<br />\r\nKesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)&nbsp;</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\n<br />\r\nAyana</p>\r\n\r\n<p>- Size : 115 x 115 cm<br />\r\n- Material : Voal Premium<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone)</p>\r\n\r\n<p>Material : Premium Voal (lembut, adem, mudah dibentuk, tegak sempurna di dahi). &nbsp;Finishing Laser cut.&nbsp;Laser cut berbentuk awan yang unik. Size : 115cm X 115cm With Packaging Box Spot UV</p>\r\n', 'produk1610769355.jpg', 1, '2021-01-16 03:55:55'),
(12, 11, 'Monalisa Mocca', 399000, '<p>NFORMASI PRODUK<br />\r\n<br />\r\nMonalisa Mocca<br />\r\n<br />\r\n- Ukuran: S, M, L, XL<br />\r\n- Bahan: Voal Premium<br />\r\n- Finishing: Laser Cut<br />\r\n<br />\r\nKesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)&nbsp;</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\n<br />\r\nMonalisa Mocca</p>\r\n\r\n<p>- Size : S, M, L, XL<br />\r\n- Material : Voal Premium<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone)</p>\r\n\r\n<p>Material : Premium Voal (lembut, adem, mudah dibentuk, tegak sempurna di dahi). &nbsp;Finishing Laser cut.&nbsp;Laser cut berbentuk awan yang unik. Size : 115cm X 115cm With Packaging Box Spot UV</p>\r\n', 'produk1610844226.JPG', 1, '2021-01-17 00:43:46'),
(13, 11, 'Fancy Dress', 499000, '<p>NFORMASI PRODUK<br />\r\nFancy Dress<br />\r\n<br />\r\n- Ukuran: S, M, L, XL<br />\r\n- Bahan: Voal Premium<br />\r\n- Finishing: Laser Cut<br />\r\n<br />\r\nKesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)&nbsp;</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\n<br />\r\nFancy Dress</p>\r\n\r\n<p>- Size : S, M, L, XL<br />\r\n- Material : Voal Premium<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone)</p>\r\n\r\n<p>Material : Premium Voal (lembut, adem, mudah dibentuk, tegak sempurna di dahi). &nbsp;Finishing Laser cut.&nbsp;Laser cut berbentuk awan yang unik. Size : 115cm X 115cm With Packaging Box Spot UV</p>\r\n', 'produk1610845558.jpg', 1, '2021-01-17 01:05:58'),
(14, 11, 'Mynisa Dress', 499000, '<p>NFORMASI PRODUK<br />\r\n<br />\r\nMynisa Dress<br />\r\n<br />\r\n- Ukuran: S, M, L, XL<br />\r\n- Bahan: Voal Premium<br />\r\n- Finishing: Laser Cut<br />\r\n<br />\r\nKesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)&nbsp;</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\n<br />\r\nMynisa Dress</p>\r\n\r\n<p>- Size : S, M, L, XL<br />\r\n- Material : Voal Premium<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone)</p>\r\n\r\n<p>Material : Premium Voal (lembut, adem, mudah dibentuk, tegak sempurna di dahi). &nbsp;Finishing Laser cut.&nbsp;Laser cut berbentuk awan yang unik. Size : 115cm X 115cm With Packaging Box Spot UV</p>\r\n', 'produk1610845664.jpeg', 1, '2021-01-17 01:07:44'),
(15, 11, 'Favinca Dress', 499000, '<p>INFORMASI PRODUK<br />\r\nFavinca Dress<br />\r\n<br />\r\n- Ukuran: S, M, L, XL<br />\r\n- Bahan: Voal Premium<br />\r\n- Finishing: Laser Cut<br />\r\n<br />\r\nKesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)&nbsp;</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\n<br />\r\nFavinca Dress</p>\r\n\r\n<p>- Size : S, M, L, XL<br />\r\n- Material : Voal Premium<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone)</p>\r\n\r\n<p>Material : Premium Voal (lembut, adem, mudah dibentuk, tegak sempurna di dahi). &nbsp;Finishing Laser cut.&nbsp;Laser cut berbentuk awan yang unik. Size : 115cm X 115cm With Packaging Box Spot UV</p>\r\n', 'produk1610845755.png', 1, '2021-01-17 01:09:15'),
(16, 11, 'Favinca Grey', 449000, '<p>INFORMASI PRODUK<br />\r\nFavinca&nbsp;Grey<br />\r\n<br />\r\n- Ukuran: S, M, L, XL<br />\r\n- Bahan: Voal Premium<br />\r\n- Finishing: Laser Cut<br />\r\n<br />\r\nKesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)&nbsp;</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\n<br />\r\nFavinca&nbsp;Grey</p>\r\n\r\n<p>- Size : S, M, L, XL<br />\r\n- Material : Voal Premium<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone)</p>\r\n\r\n<p>Material : Premium Voal (lembut, adem, mudah dibentuk, tegak sempurna di dahi). &nbsp;Finishing Laser cut.&nbsp;Laser cut berbentuk awan yang unik. Size : 115cm X 115cm With Packaging Box Spot UV</p>\r\n', 'produk1610845876.jpg', 1, '2021-01-17 01:11:16'),
(17, 11, 'White Glamour Dress', 599000, '<p>INFORMASI PRODUK<br />\r\nWhite Glamour Dress<br />\r\n<br />\r\n- Ukuran: S, M, L, XL<br />\r\n- Bahan: Voal Premium<br />\r\n- Finishing: Laser Cut<br />\r\n<br />\r\nKesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)&nbsp;</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\n<br />\r\nWhite Glamour Dress</p>\r\n\r\n<p>- Size : S, M, L, XL<br />\r\n- Material : Voal Premium<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone)</p>\r\n\r\n<p>Material : Premium Voal (lembut, adem, mudah dibentuk, tegak sempurna di dahi). &nbsp;Finishing Laser cut.&nbsp;Laser cut berbentuk awan yang unik. Size : 115cm X 115cm With Packaging Box Spot UV</p>\r\n', 'produk1610846001.jpg', 1, '2021-01-17 01:13:21'),
(18, 11, 'White Fancy Dress', 599000, '<p>INFORMASI PRODUK<br />\r\nWhite Fancy Dress<br />\r\n<br />\r\n- Ukuran: S, M, L, XL<br />\r\n- Bahan: Voal Premium<br />\r\n- Finishing: Laser Cut<br />\r\n<br />\r\nKesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)&nbsp;</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\n<br />\r\nWhite Fancy Dress</p>\r\n\r\n<p>- Size : S, M, L, XL<br />\r\n- Material : Voal Premium<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone)</p>\r\n\r\n<p>Material : Premium Voal (lembut, adem, mudah dibentuk, tegak sempurna di dahi). &nbsp;Finishing Laser cut.&nbsp;Laser cut berbentuk awan yang unik. Size : 115cm X 115cm With Packaging Box Spot UV</p>\r\n', 'produk1610846069.jpg', 1, '2021-01-17 01:14:29'),
(19, 11, 'Mysita Dress Mood', 599000, '<p>INFORMASI PRODUK<br />\r\nMysita Dress Mood<br />\r\n<br />\r\n- Ukuran: S, M, L, XL<br />\r\n- Bahan: Voal Premium<br />\r\n- Finishing: Laser Cut<br />\r\n<br />\r\nKesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)&nbsp;</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\n<br />\r\nMysita Dress Mood</p>\r\n\r\n<p>- Size : S, M, L, XL<br />\r\n- Material : Voal Premium<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone)</p>\r\n\r\n<p>Material : Premium Voal (lembut, adem, mudah dibentuk, tegak sempurna di dahi). &nbsp;Finishing Laser cut.&nbsp;Laser cut berbentuk awan yang unik. Size : 115cm X 115cm With Packaging Box Spot UV</p>\r\n', 'produk1610846167.jpg', 1, '2021-01-17 01:16:07'),
(20, 11, 'Mysita Dress Feed', 599000, '<p>INFORMASI PRODUK<br />\r\nMysita Dress Feed<br />\r\n<br />\r\n- Ukuran: S, M, L, XL<br />\r\n- Bahan: Voal Premium<br />\r\n- Finishing: Laser Cut<br />\r\n<br />\r\nKesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)&nbsp;</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\n<br />\r\nMysita Dress Feed</p>\r\n\r\n<p>- Size : S, M, L, XL<br />\r\n- Material : Voal Premium<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone)</p>\r\n\r\n<p>Material : Premium Voal (lembut, adem, mudah dibentuk, tegak sempurna di dahi). &nbsp;Finishing Laser cut.&nbsp;Laser cut berbentuk awan yang unik. Size : 115cm X 115cm With Packaging Box Spot UV</p>\r\n', 'produk1610846316.jpg', 1, '2021-01-17 01:18:36'),
(21, 11, 'Favinca Blaas', 449000, '<p>INFORMASI PRODUK<br />\r\nFavinca Blaas<br />\r\n<br />\r\n- Ukuran: S, M, L, XL<br />\r\n- Bahan: Voal Premium<br />\r\n- Finishing: Laser Cut<br />\r\n<br />\r\nKesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)&nbsp;</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\nFavinca Blaas</p>\r\n\r\n<p>- Size : S, M, L, XL<br />\r\n- Material : Voal Premium<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone)</p>\r\n\r\n<p>Material : Premium Voal (lembut, adem, mudah dibentuk, tegak sempurna di dahi). &nbsp;Finishing Laser cut.&nbsp;Laser cut berbentuk awan yang unik. Size : 115cm X 115cm With Packaging Box Spot UV</p>\r\n', 'produk1610846451.jpeg', 1, '2021-01-17 01:20:51'),
(22, 11, 'Mynisa Dress Poonk', 449000, '<p>INFORMASI PRODUK<br />\r\nMynisa Dress Poonk<br />\r\n<br />\r\n- Ukuran: S, M, L, XL<br />\r\n- Bahan: Voal Premium<br />\r\n- Finishing: Laser Cut<br />\r\n<br />\r\nKesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)&nbsp;</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\nMynisa Dress Poonk</p>\r\n\r\n<p>- Size : S, M, L, XL<br />\r\n- Material : Voal Premium<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone)</p>\r\n\r\n<p>Material : Premium Voal (lembut, adem, mudah dibentuk, tegak sempurna di dahi). &nbsp;Finishing Laser cut.&nbsp;Laser cut berbentuk awan yang unik. Size : 115cm X 115cm With Packaging Box Spot UV</p>\r\n', 'produk1610846528.jpg', 1, '2021-01-17 01:22:08'),
(23, 11, 'White Goun Mullica', 559000, '<p>INFORMASI PRODUK<br />\r\nWhite Goun Mullica<br />\r\n- Ukuran: S, M, L, XL<br />\r\n- Bahan: Voal Premium<br />\r\n- Finishing: Laser Cut<br />\r\n<br />\r\nKesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)&nbsp;</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\nWhite Goun Mullica</p>\r\n\r\n<p>- Size : S, M, L, XL<br />\r\n- Material : Voal Premium<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone)</p>\r\n\r\n<p>Material : Premium Voal (lembut, adem, mudah dibentuk, tegak sempurna di dahi). &nbsp;Finishing Laser cut.&nbsp;Laser cut berbentuk awan yang unik. Size : 115cm X 115cm With Packaging Box Spot UV</p>\r\n', 'produk1610846653.jpg', 1, '2021-01-17 01:24:13'),
(24, 11, 'Brebre Style Bun', 449000, '<p>INFORMASI PRODUK<br />\r\nBrebre Style Bun</p>\r\n\r\n<p>- Ukuran: S, M, L, XL<br />\r\n- Bahan: Voal Premium<br />\r\n- Finishing: Laser Cut</p>\r\n\r\n<p>Kesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\nBrebre Style Bun</p>\r\n\r\n<p>- Size : S, M, L, XL<br />\r\n- Material : Voal Premium<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone)</p>\r\n\r\n<p>Material : Premium Voal (lembut, adem, mudah dibentuk, tegak sempurna di dahi).&nbsp; Finishing Laser cut. Laser cut berbentuk awan yang unik. Size : 115cm X 115cm With Packaging Box Spot UV</p>\r\n', 'produk1610846830.jpg', 1, '2021-01-17 01:27:10'),
(25, 11, 'Favinca Blaas', 399000, '<p>INFORMASI PRODUK<br />\r\nFavinca Blaas</p>\r\n\r\n<p>- Ukuran: S, M, L, XL<br />\r\n- Bahan: Voal Premium<br />\r\n- Finishing: Laser Cut</p>\r\n\r\n<p>Kesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\nFavinca Blaas</p>\r\n\r\n<p>- Size : S, M, L, XL<br />\r\n- Material : Voal Premium<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone)</p>\r\n\r\n<p>Material : Premium Voal (lembut, adem, mudah dibentuk, tegak sempurna di dahi).&nbsp; Finishing Laser cut. Laser cut berbentuk awan yang unik. Size : 115cm X 115cm With Packaging Box Spot UV</p>\r\n', 'produk1610846905.jpg', 1, '2021-01-17 01:28:25'),
(26, 11, 'Favinca Blaas Mood', 399000, '<p>INFORMASI PRODUK<br />\r\nFavinca Blaas Mood</p>\r\n\r\n<p>- Ukuran: S, M, L, XL<br />\r\n- Bahan: Voal Premium<br />\r\n- Finishing: Laser Cut</p>\r\n\r\n<p>Kesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\nFavinca Blaas Mood</p>\r\n\r\n<p>- Size : S, M, L, XL<br />\r\n- Material : Voal Premium<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone)</p>\r\n\r\n<p>Material : Premium Voal (lembut, adem, mudah dibentuk, tegak sempurna di dahi).&nbsp; Finishing Laser cut. Laser cut berbentuk awan yang unik. Size : 115cm X 115cm With Packaging Box Spot UV</p>\r\n', 'produk1610847004.jpeg', 1, '2021-01-17 01:30:04'),
(27, 11, 'Favinca Blaas Poonk', 449000, '<p>INFORMASI PRODUK<br />\r\nFavinca Blaas Poonk</p>\r\n\r\n<p>- Ukuran: S, M, L, XL<br />\r\n- Bahan: Voal Premium<br />\r\n- Finishing: Laser Cut</p>\r\n\r\n<p>Kesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\nFavinca Blaas Poonk</p>\r\n\r\n<p>- Size : S, M, L, XL<br />\r\n- Material : Voal Premium<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone)</p>\r\n\r\n<p>Material : Premium Voal (lembut, adem, mudah dibentuk, tegak sempurna di dahi).&nbsp; Finishing Laser cut. Laser cut berbentuk awan yang unik. Size : 115cm X 115cm With Packaging Box Spot UV</p>\r\n', 'produk1610847071.jpg', 1, '2021-01-17 01:31:11'),
(28, 11, 'Janisca Style', 449000, '<p>INFORMASI PRODUK<br />\r\nJanisca Style</p>\r\n\r\n<p>- Ukuran: S, M, L, XL<br />\r\n- Bahan: Voal Premium<br />\r\n- Finishing: Laser Cut</p>\r\n\r\n<p>Kesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\nJanisca Style</p>\r\n\r\n<p>- Size : S, M, L, XL<br />\r\n- Material : Voal Premium<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone)</p>\r\n\r\n<p>Material : Premium Voal (lembut, adem, mudah dibentuk, tegak sempurna di dahi).&nbsp; Finishing Laser cut. Laser cut berbentuk awan yang unik. Size : 115cm X 115cm With Packaging Box Spot UV</p>\r\n', 'produk1610847175.jpg', 1, '2021-01-17 01:32:55'),
(29, 11, 'Hauri Black', 559000, '<p>INFORMASI PRODUK<br />\r\nHauri Black</p>\r\n\r\n<p>- Ukuran: S, M, L, XL<br />\r\n- Bahan: Voal Premium<br />\r\n- Finishing: Laser Cut</p>\r\n\r\n<p>Kesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\nHauri Black</p>\r\n\r\n<p>- Size : S, M, L, XL<br />\r\n- Material : Voal Premium<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone)</p>\r\n\r\n<p>Material : Premium Voal (lembut, adem, mudah dibentuk, tegak sempurna di dahi).&nbsp; Finishing Laser cut. Laser cut berbentuk awan yang unik. Size : 115cm X 115cm With Packaging Box Spot UV</p>\r\n', 'produk1610847239.jpg', 1, '2021-01-17 01:33:59'),
(30, 11, 'Hauri Norma', 399000, '<p>INFORMASI PRODUK<br />\r\nHauri Norma</p>\r\n\r\n<p>- Ukuran: S, M, L, XL<br />\r\n- Bahan: Voal Premium<br />\r\n- Finishing: Laser Cut</p>\r\n\r\n<p>Kesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\nHauri Norma</p>\r\n\r\n<p>- Size : S, M, L, XL<br />\r\n- Material : Voal Premium<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone)</p>\r\n\r\n<p>Material : Premium Voal (lembut, adem, mudah dibentuk, tegak sempurna di dahi).&nbsp; Finishing Laser cut. Laser cut berbentuk awan yang unik. Size : 115cm X 115cm With Packaging Box Spot UV</p>\r\n', 'produk1610847351.jpg', 1, '2021-01-17 01:35:51'),
(31, 11, 'Baby Blue by Mannisa', 449000, '<p>INFORMASI PRODUK<br />\r\nBaby Blue by Mannisa</p>\r\n\r\n<p>- Ukuran: S, M, L, XL<br />\r\n- Bahan: Voal Premium<br />\r\n- Finishing: Laser Cut</p>\r\n\r\n<p>Kesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\nBaby Blue by Mannisa</p>\r\n\r\n<p>- Size : S, M, L, XL<br />\r\n- Material : Voal Premium<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone)</p>\r\n\r\n<p>Material : Premium Voal (lembut, adem, mudah dibentuk, tegak sempurna di dahi).&nbsp; Finishing Laser cut. Laser cut berbentuk awan yang unik. Size : 115cm X 115cm With Packaging Box Spot UV</p>\r\n', 'produk1610847532.jpg', 1, '2021-01-17 01:38:52'),
(32, 11, 'Hipwee by Mynisa', 449000, '<p>INFORMASI PRODUK<br />\r\nHipwee by Mynisa</p>\r\n\r\n<p>- Ukuran: S, M, L, XL<br />\r\n- Bahan: Voal Premium<br />\r\n- Finishing: Laser Cut</p>\r\n\r\n<p>Kesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\nHipwee by Mynisa</p>\r\n\r\n<p>- Size : S, M, L, XL<br />\r\n- Material : Voal Premium<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone)</p>\r\n\r\n<p>Material : Premium Voal (lembut, adem, mudah dibentuk, tegak sempurna di dahi).&nbsp; Finishing Laser cut. Laser cut berbentuk awan yang unik. Size : 115cm X 115cm With Packaging Box Spot UV</p>\r\n', 'produk1610847697.jpg', 1, '2021-01-17 01:41:37'),
(33, 11, 'Norma Hauri Glow', 599000, '<p>INFORMASI PRODUK<br />\r\nNorma Hauri Glow</p>\r\n\r\n<p>- Ukuran: S, M, L, XL<br />\r\n- Bahan: Voal Premium<br />\r\n- Finishing: Laser Cut</p>\r\n\r\n<p>Kesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\nNorma Hauri Glow</p>\r\n\r\n<p>- Size : S, M, L, XL<br />\r\n- Material : Voal Premium<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone)</p>\r\n\r\n<p>Material : Premium Voal (lembut, adem, mudah dibentuk, tegak sempurna di dahi).&nbsp; Finishing Laser cut. Laser cut berbentuk awan yang unik. Size : 115cm X 115cm With Packaging Box Spot UV</p>\r\n', 'produk1610847829.jpg', 1, '2021-01-17 01:43:49'),
(34, 11, 'Favinca Dress white', 559000, '<p>INFORMASI PRODUK<br />\r\nFavinca Dress white</p>\r\n\r\n<p>- Ukuran: S, M, L, XL<br />\r\n- Bahan: Voal Premium<br />\r\n- Finishing: Laser Cut</p>\r\n\r\n<p>Kesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\nFavinca Dress white</p>\r\n\r\n<p>- Size : S, M, L, XL<br />\r\n- Material : Voal Premium<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone)</p>\r\n\r\n<p>Material : Premium Voal (lembut, adem, mudah dibentuk, tegak sempurna di dahi).&nbsp; Finishing Laser cut. Laser cut berbentuk awan yang unik. Size : 115cm X 115cm With Packaging Box Spot UV</p>\r\n', 'produk1610847950.jpg', 1, '2021-01-17 01:45:50'),
(35, 11, 'Hauri Norma Red', 299000, '<p>INFORMASI PRODUK<br />\r\nHauri Norma Red</p>\r\n\r\n<p>- Ukuran: S, M, L, XL<br />\r\n- Bahan: Voal Premium<br />\r\n- Finishing: Laser Cut</p>\r\n\r\n<p>Kesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\nHauri Norma Red</p>\r\n\r\n<p>- Size : S, M, L, XL<br />\r\n- Material : Voal Premium<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone)</p>\r\n\r\n<p>Material : Premium Voal (lembut, adem, mudah dibentuk, tegak sempurna di dahi).&nbsp; Finishing Laser cut. Laser cut berbentuk awan yang unik. Size : 115cm X 115cm With Packaging Box Spot UV</p>\r\n', 'produk1610848032.jpg', 1, '2021-01-17 01:47:12'),
(36, 12, 'Simple Head Band', 79000, '<p>INFORMASI PRODUK<br />\r\nSimple Head Band</p>\r\n\r\n<p>- Ukuran: 30 cm<br />\r\n- Berat : 90 gram<br />\r\n- Finishing: Laser Cut</p>\r\n\r\n<p>Kesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\nSimple Head Band</p>\r\n\r\n<p>- Size : 38 cm<br />\r\n- Weight : 90 gram<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone)</p>\r\n', 'produk1610848447.jpg', 1, '2021-01-17 01:54:07'),
(37, 12, 'Fancy Head Band', 79000, '<p><br />\r\nINFORMASI PRODUK<br />\r\nSimple Head Band</p>\r\n\r\n<p>- Ukuran: 30 cm<br />\r\n- Berat : 90 gram<br />\r\n- Finishing: Laser Cut</p>\r\n\r\n<p>Kesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\nFancy Head Band</p>\r\n\r\n<p>- Size : 38 cm<br />\r\n- Weight : 90 gram<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone)</p>\r\n', 'produk1610848549.jpg', 1, '2021-01-17 01:55:49'),
(38, 11, 'Pink Cute by Mysita', 599000, '<p>INFORMASI PRODUK<br />\r\nPink Cute by Mysita</p>\r\n\r\n<p>- Ukuran: S, M, L, XL<br />\r\n- Bahan: Voal Premium<br />\r\n- Finishing: Laser Cut</p>\r\n\r\n<p>Kesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\nPink Cute by Mysita</p>\r\n\r\n<p>- Size : S, M, L, XL<br />\r\n- Material : Voal Premium<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone)</p>\r\n\r\n<p>Material : Premium Voal (lembut, adem, mudah dibentuk, tegak sempurna di dahi).&nbsp; Finishing Laser cut. Laser cut berbentuk awan yang unik. Size : 115cm X 115cm With Packaging Box Spot UV</p>\r\n\r\n<p>&nbsp;</p>\r\n', 'produk1610848687.jpg', 1, '2021-01-17 01:58:07'),
(39, 12, 'Blue Bag', 300000, '<p>NFORMASI PRODUK<br />\r\nBlue Bag</p>\r\n\r\n<p>- Ukuran: 30 cm<br />\r\n- Berat : 90 gram<br />\r\n- Finishing: Laser Cut</p>\r\n\r\n<p>Kesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\nBlue Bag</p>\r\n\r\n<p>- Size : 38 cm<br />\r\n- Weight : 90 gram<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone)</p>\r\n', 'produk1610849713.jpg', 1, '2021-01-17 02:15:13'),
(40, 12, 'Vanisa Clutch', 599000, '<p>INFORMASI PRODUK<br />\r\nVanisa Clutch</p>\r\n\r\n<p>- Ukuran: 38 cm<br />\r\n- Berat : 90 gram<br />\r\n- Finishing: Laser Cut</p>\r\n\r\n<p>Kesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\nVanisa Clutch</p>\r\n\r\n<p>- Size : 38 cm<br />\r\n- Weight : 90 gram<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone)</p>\r\n', 'produk1610849869.jpg', 1, '2021-01-17 02:17:49'),
(41, 12, 'BB by Mynoera', 249000, '<p>NFORMASI PRODUK<br />\r\nBB by Mynoera</p>\r\n\r\n<p>- Ukuran: 36, 37, 39, 40,41<br />\r\n- Berat : 90 gram<br />\r\n- Finishing: Laser Cut</p>\r\n\r\n<p>Kesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\nBB by Mynoera</p>\r\n\r\n<p>- Size : 36, 37, 39, 40,41<br />\r\n- Weight : 90 gram<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone)</p>\r\n', 'produk1610850473.jpg', 1, '2021-01-17 02:27:53'),
(42, 12, 'Fancys by Mynoera', 249000, '<p><br />\r\nNFORMASI PRODUK<br />\r\nFancys by Mynoera</p>\r\n\r\n<p>- Ukuran: 36, 37, 39, 40,41<br />\r\n- Berat : 90 gram<br />\r\n- Finishing: Laser Cut</p>\r\n\r\n<p>Kesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\nFancys by Mynoera</p>\r\n\r\n<p>- Size : 36, 37, 39, 40,41<br />\r\n- Weight : 90 gram<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone)</p>\r\n', 'produk1610850602.jpg', 1, '2021-01-17 02:30:02'),
(43, 12, 'Star Cute', 449000, '<p><br />\r\nNFORMASI PRODUK<br />\r\nStar Cute</p>\r\n\r\n<p>- Ukuran: 36, 37, 39, 40,41<br />\r\n- Berat : 90 gram<br />\r\n- Finishing: Laser Cut</p>\r\n\r\n<p>Kesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\nStar Cute</p>\r\n\r\n<p>- Size :36, 37, 39, 40,41<br />\r\n- Weight : 90 gram<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone)</p>\r\n', 'produk1610850673.jpg', 1, '2021-01-17 02:31:13'),
(44, 12, 'Cavana Sneekers', 350000, '<p><br />\r\nNFORMASI PRODUK<br />\r\nCavana Sneekers</p>\r\n\r\n<p>- Ukuran: 36, 37, 39, 40,41<br />\r\n- Berat : 90 gram<br />\r\n- Finishing: Laser Cut</p>\r\n\r\n<p>Kesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\nCavana Sneekers</p>\r\n\r\n<p>- Size : 38 cm<br />\r\n- Weight : 90 gram<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone)</p>\r\n', 'produk1610850733.jpg', 1, '2021-01-17 02:32:13'),
(45, 12, 'converse sneekers', 199000, '<p><br />\r\nNFORMASI PRODUK<br />\r\nconverse sneekers</p>\r\n\r\n<p>- Ukuran: 36, 37, 39, 40,41<br />\r\n- Berat : 90 gram<br />\r\n- Finishing: Laser Cut</p>\r\n\r\n<p>Kesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\nconverse sneekers</p>\r\n\r\n<p>- Size : 36, 37, 39, 40,41<br />\r\n- Weight : 90 gram<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone)</p>\r\n', 'produk1610860709.jpg', 1, '2021-01-17 05:18:30'),
(46, 12, 'Vania Clutch', 499000, '<p>INFORMASI PRODUK<br />\r\nVanisa Clutch</p>\r\n\r\n<p>- Ukuran: 38 cm<br />\r\n- Berat : 90 gram<br />\r\n- Finishing: Laser Cut</p>\r\n\r\n<p>Kesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\nVanisa Clutch</p>\r\n\r\n<p>- Size : 38 cm<br />\r\n- Weight : 90 gram<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone)</p>\r\n', 'produk1610860845.jpg', 1, '2021-01-17 05:20:45'),
(47, 12, 'B&B by Mynoera', 249000, '<p>NFORMASI PRODUK<br />\r\nB&amp;B by Mynoera</p>\r\n\r\n<p>- Ukuran: 36, 37, 39, 40,41<br />\r\n- Berat : 90 gram<br />\r\n- Finishing: Laser Cut</p>\r\n\r\n<p>Kesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\nCavana Sneekers</p>\r\n\r\n<p>- Size : 36, 37, 39, 40,41<br />\r\n- Weight : 90 gram<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone</p>\r\n', 'produk1610861051.jpg', 1, '2021-01-17 05:24:11'),
(48, 12, 'Feminine by Masy', 499000, '<p>NFORMASI PRODUK<br />\r\nFeminine by Masy</p>\r\n\r\n<p>- Ukuran: 36, 37, 39, 40,41<br />\r\n- Berat : 90 gram<br />\r\n- Finishing: Laser Cut</p>\r\n\r\n<p>Kesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\nFeminine by Masy</p>\r\n\r\n<p>- Size : 36, 37, 39, 40,41<br />\r\n- Weight : 90 gram<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone</p>\r\n', 'produk1610861166.jpg', 1, '2021-01-17 05:26:06'),
(49, 7, 'Blue Fancy', 149000, '<p>INFORMASI PRODUK<br />\r\n<br />\r\nBlue Fancy<br />\r\n<br />\r\n- Ukuran: 115 x 115 cm<br />\r\n- Bahan: Voal Premium<br />\r\n- Finishing: Laser Cut<br />\r\n<br />\r\nKesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)&nbsp;</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\n<br />\r\nBlue Fancy</p>\r\n\r\n<p>- Size : 115 x 115 cm<br />\r\n- Material : Voal Premium<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone)</p>\r\n', 'produk1610861709.jpg', 1, '2021-01-17 05:35:09'),
(50, 7, 'A&S Scarf', 149000, '<p>INFORMASI PRODUK<br />\r\n<br />\r\nA&amp;S Scarf<br />\r\n<br />\r\n- Ukuran: 115 x 115 cm<br />\r\n- Bahan: Voal Premium<br />\r\n- Finishing: Laser Cut<br />\r\n<br />\r\nKesamaan warna dengan yang asli 98% (karena efek cahaya dan layar masing-masing perangkat)&nbsp;</p>\r\n\r\n<p>PRODUCT INFORMATION<br />\r\n<br />\r\nA&amp;S Scarf</p>\r\n\r\n<p>- Size : 115 x 115 cm<br />\r\n- Material : Voal Premium<br />\r\n- Finishing : Laser Cut</p>\r\n\r\n<p>Color of similarity to the original 98% (due to the light effect and screen of each handphone)</p>\r\n\r\n<p>&nbsp;</p>\r\n', 'produk1610861864.jpeg', 1, '2021-01-17 05:37:44');

--
-- Indexes for dumped tables
--

--
-- Indeks untuk tabel `db_admin`
--
ALTER TABLE `db_admin`
  ADD PRIMARY KEY (`admin_id`);

--
-- Indeks untuk tabel `db_category`
--
ALTER TABLE `db_category`
  ADD PRIMARY KEY (`category_id`);

--
-- Indeks untuk tabel `dp_product`
--
ALTER TABLE `dp_product`
  ADD PRIMARY KEY (`product_id`),
  ADD KEY `category_id` (`category_id`);

--
-- AUTO_INCREMENT untuk tabel yang dibuang
--

--
-- AUTO_INCREMENT untuk tabel `db_admin`
--
ALTER TABLE `db_admin`
  MODIFY `admin_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT untuk tabel `db_category`
--
ALTER TABLE `db_category`
  MODIFY `category_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=13;

--
-- AUTO_INCREMENT untuk tabel `dp_product`
--
ALTER TABLE `dp_product`
  MODIFY `product_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=51;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
